'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { getCreativesForBrand } from '@/app/actions/creatives'

type Creative = Awaited<ReturnType<typeof getCreativesForBrand>>[number]

const FORMAT_LABEL: Record<string, string> = {
  INSTAGRAM_SQUARE: 'Instagram Square',
  INSTAGRAM_STORY: 'Instagram Story',
  LINKEDIN_POST: 'LinkedIn Post',
  LINKEDIN_BANNER: 'LinkedIn Banner',
}

const FORMAT_ASPECT: Record<string, string> = {
  INSTAGRAM_SQUARE: '100%',
  INSTAGRAM_STORY: '177.8%',
  LINKEDIN_POST: '52.4%',
  LINKEDIN_BANNER: '33.3%',
}

const DOWNLOAD_FORMATS = [
  { label: 'JPG', value: 'jpg' },
  { label: 'PNG', value: 'png' },
  { label: 'WebP', value: 'webp' },
]

const MARKETING_FACTS = [
  { stat: '3–4×', text: 'more brand visibility with consistent visuals across channels.' },
  { stat: '0.05s', text: "is all it takes for a consumer to form an opinion about your brand's look." },
  { stat: '80%', text: 'increase in brand recognition when you use a consistent color palette.' },
  { stat: '40×', text: 'more likely — visual content gets shared over plain text.' },
  { stat: '22%', text: 'more engagement on Instagram posts with a cohesive aesthetic.' },
  { stat: '85%', text: 'of consumers are more likely to buy after seeing consistent brand imagery.' },
  { stat: '33%', text: 'more revenue generated by companies with strong, consistent branding.' },
  { stat: '94%', text: 'of first impressions are design-related — before a single word is read.' },
]

function MarketingFactsBanner() {
  const [index, setIndex] = useState(0)
  const [visible, setVisible] = useState(true)

  useEffect(() => {
    const timer = setInterval(() => {
      setVisible(false)
      setTimeout(() => {
        setIndex(i => (i + 1) % MARKETING_FACTS.length)
        setVisible(true)
      }, 400)
    }, 4000)
    return () => clearInterval(timer)
  }, [])

  const fact = MARKETING_FACTS[index]
  return (
    <div
      className="rounded-2xl p-5 mb-8 flex items-center gap-5"
      style={{ background: 'linear-gradient(135deg, rgba(124,58,237,0.12), rgba(255,107,107,0.08))', border: '1px solid rgba(124,58,237,0.2)' }}
    >
      <div className="flex-shrink-0 w-10 h-10 rounded-xl flex items-center justify-center text-xl" style={{ background: 'rgba(124,58,237,0.2)' }}>
        ✨
      </div>
      <div className="flex-1 min-w-0" style={{ transition: 'opacity 0.4s', opacity: visible ? 1 : 0 }}>
        <p className="text-xs text-white/40 mb-0.5 uppercase tracking-wide font-medium">Did you know?</p>
        <p className="text-sm text-white">
          <span className="font-bold text-brand-300 text-base mr-1">{fact.stat}</span>
          {fact.text}
        </p>
      </div>
      <div className="flex gap-1 flex-shrink-0">
        {MARKETING_FACTS.map((_, i) => (
          <div key={i} className="w-1.5 h-1.5 rounded-full transition-all" style={{ background: i === index ? '#7C3AED' : 'rgba(255,255,255,0.15)' }} />
        ))}
      </div>
    </div>
  )
}

function SkeletonCard({ format }: { format: string }) {
  return (
    <div className="rounded-2xl overflow-hidden" style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.09)' }}>
      <div className="relative overflow-hidden" style={{ paddingBottom: FORMAT_ASPECT[format] ?? '100%', background: 'rgba(255,255,255,0.04)' }}>
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="text-center">
            <div className="w-8 h-8 rounded-full animate-spin mx-auto mb-3"
                 style={{ border: '2px solid rgba(255,255,255,0.1)', borderTop: '2px solid #7C3AED' }} />
            <p className="text-white/35 text-xs">Generating…</p>
          </div>
        </div>
        <div className="absolute inset-0 animate-pulse" style={{ background: 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.03) 50%, transparent 100%)', backgroundSize: '200% 100%' }} />
      </div>
      <div className="p-4 space-y-2">
        <div className="h-3 rounded w-2/3 animate-pulse" style={{ background: 'rgba(255,255,255,0.07)' }} />
        <div className="h-2.5 rounded w-1/3 animate-pulse" style={{ background: 'rgba(255,255,255,0.04)' }} />
      </div>
    </div>
  )
}

function CreativeCardItem({ creative, brandId }: { creative: Creative; brandId: string }) {
  const [visible, setVisible] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (creative.status !== 'COMPLETED') return
    requestAnimationFrame(() => setVisible(true))
  }, [creative.status])

  if (creative.status !== 'COMPLETED' && creative.status !== 'FAILED') {
    return <SkeletonCard format={creative.format} />
  }

  return (
    <div
      ref={ref}
      className="rounded-2xl overflow-hidden transition-all duration-500 group"
      style={{
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.09)',
        opacity: visible ? 1 : 0,
        transform: visible ? 'scale(1)' : 'scale(0.97)',
      }}
    >
      <div className="relative overflow-hidden" style={{ paddingBottom: FORMAT_ASPECT[creative.format] ?? '100%', background: 'rgba(0,0,0,0.3)' }}>
        {creative.status === 'COMPLETED' && creative.url ? (
          <img
            src={creative.url}
            alt={FORMAT_LABEL[creative.format] || creative.format}
            className="absolute inset-0 w-full h-full object-cover"
          />
        ) : (
          <div className="absolute inset-0 flex items-center justify-center">
            <p className="text-[#FCA5A5] text-xs font-medium">Generation failed</p>
          </div>
        )}
        {creative.variantIndex > 0 && (
          <div className="absolute top-2 left-2 text-xs px-2 py-0.5 rounded-full font-medium"
               style={{ background: 'rgba(0,0,0,0.65)', color: 'rgba(255,255,255,0.8)' }}>
            Variant {creative.variantIndex + 1}
          </div>
        )}
      </div>

      <div className="p-4">
        <p className="text-sm font-medium text-white mb-0.5">{FORMAT_LABEL[creative.format] || creative.format}</p>
        <p className="text-xs text-white/35 mb-3">{new Date(creative.createdAt).toLocaleDateString()}</p>

        <div className="flex gap-2 flex-wrap">
          <Link
            href={`/brands/${brandId}/creatives/${creative.id}`}
            className="text-xs font-medium px-3 py-1.5 rounded-lg transition-colors"
            style={{ background: 'rgba(124,58,237,0.2)', color: '#C4B5FD', border: '1px solid rgba(124,58,237,0.3)' }}
          >
            View & Refine
          </Link>

          {creative.status === 'COMPLETED' && creative.url && (
            <div className="relative group/dl">
              <button
                className="text-xs font-medium px-3 py-1.5 rounded-lg transition-colors"
                style={{ background: 'rgba(255,255,255,0.06)', color: 'rgba(255,255,255,0.6)', border: '1px solid rgba(255,255,255,0.1)' }}
              >
                Download ▾
              </button>
              <div className="hidden group-hover/dl:flex absolute bottom-full left-0 mb-1 rounded-xl flex-col overflow-hidden z-10 min-w-[80px]"
                   style={{ background: '#1A0A2E', border: '1px solid rgba(255,255,255,0.12)' }}>
                {DOWNLOAD_FORMATS.map(fmt => (
                  <a
                    key={fmt.value}
                    href={`/api/creatives/${creative.id}/download?format=${fmt.value}`}
                    download
                    className="text-xs px-3 py-2 whitespace-nowrap text-white/70 hover:text-white hover:bg-white/8 transition-colors"
                  >
                    {fmt.label}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default function CreativesGrid({ initialCreatives, brandId }: { initialCreatives: Creative[]; brandId: string }) {
  const [creatives, setCreatives] = useState(initialCreatives)
  const allDone = creatives.every(c => c.status === 'COMPLETED' || c.status === 'FAILED')
  const hasPending = !allDone

  useEffect(() => {
    if (allDone) return
    const interval = setInterval(async () => {
      const fresh = await getCreativesForBrand(brandId)
      setCreatives(fresh)
    }, 3000)
    return () => clearInterval(interval)
  }, [brandId, allDone])

  if (creatives.length === 0) {
    return (
      <div className="text-center py-16 rounded-2xl" style={{ border: '2px dashed rgba(255,255,255,0.1)' }}>
        <p className="text-4xl mb-4">🖼</p>
        <p className="text-white/45 mb-6">No creatives generated yet.</p>
        <Link
          href={`/brands/${brandId}/creatives/new`}
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl font-semibold text-white text-sm"
          style={{ background: 'linear-gradient(135deg, #7C3AED, #FF6B6B)' }}
        >
          ✨ Generate First Creative
        </Link>
      </div>
    )
  }

  return (
    <div>
      {hasPending && <MarketingFactsBanner />}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {creatives.map(creative => (
          <CreativeCardItem key={creative.id} creative={creative} brandId={brandId} />
        ))}
      </div>
    </div>
  )
}
