'use client'
import { useEffect, useRef, useState } from 'react'

const EXAMPLES = [
  { name: 'Nova Studio', primary: '#6D28D9', accent: '#F59E0B', format: 'Instagram Square' },
  { name: 'Coral Co.', primary: '#FF6B6B', accent: '#1A1A2E', format: 'LinkedIn Post' },
  { name: 'Forest Goods', primary: '#059669', accent: '#F0FDF4', format: 'Instagram Story' },
  { name: 'Midnight Lab', primary: '#1E1B4B', accent: '#818CF8', format: 'LinkedIn Banner' },
  { name: 'Sunrise Media', primary: '#D97706', accent: '#FEF3C7', format: 'Instagram Square' },
  { name: 'Chrome Digital', primary: '#374151', accent: '#F9FAFB', format: 'LinkedIn Post' },
]

export default function SocialProofStrip() {
  const ref = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const obs = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) { setVisible(true); obs.disconnect() }
    }, { threshold: 0.1 })
    obs.observe(el)
    return () => obs.disconnect()
  }, [])

  return (
    <section className="py-16 overflow-hidden">
      <p className="text-center text-white/40 text-xs font-semibold uppercase tracking-widest mb-8 px-6">
        Generated by Brand Alchemist
      </p>
      <div
        ref={ref}
        className={`flex gap-4 px-6 overflow-x-auto scrollbar-hide transition-all duration-700 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}
        style={{ scrollbarWidth: 'none' }}
      >
        {EXAMPLES.map((ex, i) => (
          <div
            key={i}
            className="flex-shrink-0 w-48 rounded-xl overflow-hidden border border-white/10"
          >
            <div
              className="w-full h-32 flex items-center justify-center"
              style={{
                background: `linear-gradient(135deg, ${ex.primary}, ${ex.accent})`,
              }}
            >
              <div className="text-center px-3">
                <div className="w-8 h-8 rounded-full bg-white/20 mx-auto mb-2" />
                <div className="h-1.5 w-16 bg-white/40 rounded mx-auto" />
              </div>
            </div>
            <div className="bg-[#1A0030] px-3 py-2">
              <p className="text-white/80 text-xs font-medium truncate">{ex.name}</p>
              <p className="text-white/30 text-xs">{ex.format}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}
